/// TODO: Implement the registrations-request host function, blocked by missing component
/// information on host calls, fixed by adding Store context to host functions.
///
/// Relevant Zulip discussion: https://bytecodealliance.zulipchat.com/#narrow/channel/217126-wasmtime/topic/Support.20for.20identifying.20the.20guest.20making.20a.20host.20call/with/571099564
interface host-types {
    //record registrations-result {
    //    discord-events: registrations-result-discord-events-interaction-create,
    //    scheduled-jobs: list<tuple<string, string>>,
    //    dependency-functions: list<tuple<string, string>>,
    //}

    //record registrations-result-discord-events-interaction-create {
    //  application-commands: list<tuple<string, string>>,
    //  message-components: list<tuple<string, string>>,
    //  modals: list<tuple<string, string>>,
    //}

    enum log-levels {
        trace,
        debug,
        info,
        warn,
        error,
    }
}

interface host-functions {
    use host-types.{log-levels};
    use discord-types.{requests as discord-requests, responses as discord-responses};

    /// Can only be called during the initialization plugin call, calls at other times will be ignored.
    //registrations-request: func(registrations: registrations) -> result<registrations-result, string>;

    log: func(level: log-levels, message: string);

    discord-request: func(request: discord-requests) -> result<option<discord-responses>, string>;

    /// params, result Ok and Err are JSON.
    dependency-function: func(dependency: string, function: string, params: list<u8>) -> result<list<u8>, string>;

    shutdown: func(restart: bool);
}
